apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  template:
    spec:
      containers:
      - name: nfs-server
        volumeMounts:
          - mountPath: /data/wordpress
            name: data-wordpress
          - mountPath: /etc/exports
            name: exports-conf
            subPath: exports
      volumes:
        # From an existing Elastic Block Store
        - name: data-wordpress
          awsElasticBlockStore:
            volumeID: <EXISTING_EBS_VOLUME_ID>
        - name: exports-conf
          configMap:
            name: nfs-server-config
            items:
            - key: exports
              path: exports
