apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  template:
    spec:
      containers:
      - name: nfs-server
        volumeMounts:
          - mountPath: /data/wordpress
            name: data-wordpress
          - mountPath: /etc/exports
            name: exports-conf
            subPath: exports
      volumes:
        - name: exports-conf
          configMap:
            name: nfs-server-config
            items:
            - key: exports
              path: exports
  volumeClaimTemplates:
  # Create a PV from default storageclass
  - metadata:
      name: data-wordpress
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
