---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  replicas: 1
  podManagementPolicy: Parallel
  serviceName: nfs-server
  selector:
    matchLabels:
      app: nfs
      role: nfs-server
  template:
    metadata:
      labels:
        app: nfs
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        resources: {}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
