apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:php7.4-apache
        name: wordpress
        resources: {}
        ports:
        - containerPort: 80
          name: wordpress
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /wp-admin/images/wordpress-logo.svg
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /wp-admin/images/wordpress-logo.svg
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-nfs-pvc
      volumes:
      - name: wordpress-nfs-pvc
        persistentVolumeClaim:
          claimName: wordpress-nfs-pvc

