apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/data/wordpress"
  storageClassName: "nfs-local"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-local"
  resources:
    requests:
      storage: 20Gi
