apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  ports:
  - nodePort: 31639
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress


